__version__ = "2.4.0"
__app_name__ = "LAC"
__author__ = "LAC Contributors"
__description__ = "Find your perfect local LLM — scans hardware, recommends models, installs and chats"
__github_url__ = "https://github.com/Dkrynen/lac"
__download_url__ = "https://github.com/Dkrynen/lac/releases"
