__version__ = "2.2.0"
__app_name__ = "Model Hub"
__author__ = "Model Hub Contributors"
__description__ = "Hardware scanner + model recommender + installer for local LLMs"
__github_url__ = "https://github.com/Dkrynen/model-hub"
__download_url__ = "https://github.com/Dkrynen/model-hub/releases"
